dry_cleaning/apps/director/urls.py
from django.urls import path
from . import views

app_name = 'director'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
path('analysis/', views.analysis, name='analysis'),
path('accounting/', views.accounting, name='accounting')
]

dry_cleaning/apps/manager/urls.py
from django.urls import path
from . import views

app_name = 'manager'

urlpatterns = [
    path('', views.index, name='index'),
    path('dir_drugs/', views.dir_drugs, name='dir_drugs'),
    path('add_drugs/', views.add_drugs, name='add_drugs'),
    path('reg_drugs/', views.reg_drugs, name='reg_drugs'),
    path('upd_drugs/<int:id>', views.upd_drugs, name='upd_drugs'),
    path('update_drugs/<int:id>', views.update_drugs, name='update_drugs'),
    path('del_drugs/<int:id>', views.del_drugs, name='del_drugs'),

    path('dir_servs/', views.dir_servs, name='dir_servs'),
    path('add_servs/', views.add_servs, name='add_servs'),
    path('reg_servs/', views.reg_servs, name='reg_servs'),
    path('upd_servs/<int:id>', views.upd_servs, name='upd_servs'),
    path('update_servs/<int:id>', views.update_servs, name='update_servs'),
    path('del_servs/<int:id>', views.del_servs, name='del_servs'),

    path('orders/', views.orders, name='orders'),
    path('order_done/<int:id>', views.order_done, name='order_done'),


    path('orders_done/', views.orders_done, name='orders_done'),


    path('possession/', views.possession, name='possession'),
    path('add_possession/', views.add_possession, name='add_possession'),
    path('reg_possession/', views.reg_possession, name='reg_possession'),
    path('upd_possession/<int:id>', views.upd_possession, name='upd_possession'),
    path('update_possession/<int:id>', views.update_possession, name='update_possession'),
    path('del_possession/<int:id>', views.del_possession, name='del_possession'),



    path('shift/', views.shift, name='shift'),
    path('add_shift/<int:id>', views.add_shift, name='add_shift')
]

dry_cleaning/apps/receiver/urls.py
from django.urls import path
from . import views

app_name = 'receiver'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_clients/', views.add_clients, name='add_clients'),
    path('reg_clients/', views.reg_clients, name='reg_clients'),
    path('upd_clients/<int:id>', views.upd_clients, name='upd_clients'),
    path('update_clients/<int:id>', views.update_clients, name='update_clients'),
    path('del_clients/<int:id>', views.del_clients, name='del_clients'),
    path('clients/', views.clients, name='clients'),


    path('services/', views.services, name='services'),
    path('add_services/', views.add_services, name='add_services'),
    path('reg_services/', views.reg_services, name='reg_services'),
    path('orders_done/', views.orders_done, name='orders_done'),
    path('services_done/', views.services_done, name='services_done'),
    path('upd_services/<int:id>', views.upd_services, name='upd_services'),
    path('update_services/<int:id>', views.update_services, name='update_services'),
    path('del_services/<int:id>', views.del_services, name='del_services'),


    path('orders/', views.orders, name='orders'),
    path('add_order/', views.add_order, name='add_order'),
    path('reg_orders/', views.reg_orders, name='reg_orders'),
    path('upd_orders/<int:id>', views.upd_orders, name='upd_orders'),
    path('update_orders/<int:id>', views.update_orders, name='update_orders'),
    path('del_orders/<int:id>', views.del_orders, name='del_orders')
]

dry_cleaning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('authorize.urls')),
    path('director/', include('director.urls')),
    path('manager/', include('manager.urls')),
    path('receiver/', include('receiver.urls')),
    path('admin/', admin.site.urls),
]

dry_cleaning/apps/authorize/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    position = models.TextField(max_length=500, blank=True)
    phone= models.TextField(max_length=500, blank=True)
    total= models.IntegerField(null=True)

dry_cleaning/apps/director/models.py
from django.db import models


class Expenses(models.Model):
    lease = models.IntegerField()
    utilities = models.IntegerField()
    equipment = models.IntegerField()
    salary = models.IntegerField()
    materials = models.IntegerField()
    preparations = models.IntegerField()
    date= models.DateTimeField(null=True)

dry_cleaning/apps/manager/models.py
from django.db import models
from django.contrib.auth.models import User


class Chemicals(models.Model):
    name = models.TextField(max_length=50, blank=True)
    quantity = models.IntegerField(blank=True)
    type = models.TextField()
    type_by_use = models.TextField()
    instruction = models.TextField()


class Shifts(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    position = models.TextField(max_length=50, blank=True)
    spent_changes = models.IntegerField(blank=True)

class Possession(models.Model):
    name = models.TextField(max_length=50, blank=True)
    type = models.TextField(max_length=50, blank=True)
    service = models.TextField(max_length=50, blank=True)
    chemical = models.TextField(max_length=50, blank=True)
    cost = models.TextField(max_length=50, blank=True)
    hour = models.TextField(max_length=50, blank=True)
    date = models.TextField(max_length=50, blank=True)

dry_cleaning/apps/receiver/models.py
from django.db import models
from django.contrib.auth.models import User

class Client(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone = models.TextField(null=True)


class Service(models.Model):
    name = models.TextField(max_length=50, blank=True)
    time = models.TextField(blank=True)
    ownership = models.TextField(null=True)
    preparations = models.TextField(null=True)
    total = models.IntegerField(blank=True)


class Order(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    status = models.TextField(max_length=50, blank=True)
    clothes = models.TextField(max_length=50, blank=True)
    quantity = models.IntegerField(blank=True)
    date_of_receipt = models.DateTimeField(null=True)
    date_of_issue = models.DateTimeField(null=True)
    date_of_process = models.DateTimeField(null=True)
    total = models.IntegerField(blank=True)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)

dry_cleaning/apps/authorize/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.models import User
from .models import *
from django.http import HttpResponseRedirect


def index(request):
    return render(request, 'base.html')


def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('authorize:index'))


def reg(request):
    UserModel = get_user_model()
    user = UserModel.objects.create_user(username=request.POST['username'],
                                         password=request.POST['password'])
    user.save()
    profile = Profile.objects.create(user=user,
                                     position=request.POST['position'],
                                         phone=request.POST['phone'],
                                     total=0)
    profile.save()
    return HttpResponseRedirect(reverse('authorize:signin'))


def log(request):
    user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
    if user is not None:
        login(request, user)
        print('Вход осуществлён')
        return HttpResponseRedirect(reverse('authorize:index'))
    else:
        print(user)
        print('Не получилось войти')
        return HttpResponseRedirect(reverse('authorize:signin'))


def getusers(request):
    a = User.objects.all()
    return render(request, 'registration/users.html', {'users': a})


def signup(request):
    return render(request, 'signup.html')


def signin(request):
    return render(request, 'authorize/login.html')

dry_cleaning/apps/director/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'director/index.html')

def register(request):
    return render(request, 'director/reg.html')
def accounting(request):
    return render(request, 'director/accounting.html')
def analysis(request):
    return render(request, 'director/analysis.html')

dry_cleaning/apps/manager/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.models import User
from .models import *
from receiver.models import *
from authorize.models import Profile
from django.http import HttpResponseRedirect
from datetime import date

def index(request):
    return render(request, 'manager/index.html')


def orders(request):
    a = Order.objects.all()
    list=[]
    for ord in a:
        if ord.status != "Success":
            list.append(ord)
    config = {
        'orders': list
    }
    return render(request, 'manager/orders.html',config)


def order_done(request,id):
    order = Order.objects.get(id=id)
    order.status ="Success"
    order.date_of_issue = date.today()
    order.save()
    return HttpResponseRedirect(reverse('manager:orders'))


def orders_done(request):
    a = Order.objects.all()
    list = []
    for ord in a:
        if ord.status == "Success":
            list.append(ord)
    config = {
        'orders': list
    }
    return render(request, 'manager/orders_done.html',config)


def possession(request):
    a = Possession.objects.all()
    config = {
        'possessions': a
    }
    return render(request, 'manager/possession.html', config)

def add_possession(request):

    return render(request, 'manager/add_possession.html', )

def upd_possession(request, id):
    drug = Possession.objects.get(id=id)
    config = {
        'poss': drug,
    }
    return render(request, 'manager/upd_possession.html', config)


def update_possession(request, id):
    possession = Possession.objects.get(id=id)
    possession.name = request.POST['name']
    possession.type = request.POST['type']
    possession.service = request.POST['service']
    possession.chemical = request.POST['chemical']
    possession.cost = request.POST['cost']
    possession.hour = request.POST['hour']
    possession.save()
    return HttpResponseRedirect(reverse('manager:possession'))


def del_possession(request, id):
    Possession.objects.get(id=id).delete()
    return HttpResponseRedirect(reverse('manager:possession'))


def reg_possession(request):
    profile = Possession.objects.create(name= request.POST['name'],
                                     type=request.POST['type'],
                                   service=request.POST['service'],
                                    chemical = request.POST['chemical'],
                                    cost = request.POST['cost'],
                                    hour = request.POST['hour'],
                                    date = date.today())
    profile.save()
    return HttpResponseRedirect(reverse('manager:possession'))


def shift(request):
    a = Profile.objects.all()
    config = {
        'profiles': a
    }
    return render(request, 'manager/shift.html',config)

def add_shift(request,id):
    prof = Profile.objects.get(id=id)
    prof.total+=1
    prof.save()
    return HttpResponseRedirect(reverse('manager:shift'))


def dir_drugs(request):
    a = Chemicals.objects.all()
    config = {
        'drugs': a
    }
    return render(request, 'manager/dir_drugs.html',config)

def add_drugs(request):
    config = {
    }
    return render(request, 'manager/add_drugs.html', config)

def upd_drugs(request, id):
    drug = Chemicals.objects.get(id=id)
    config = {
        'drug': drug,
    }
    return render(request, 'manager/upd_drugs.html', config)


def update_drugs(request, id):
    drug = Chemicals.objects.get(id=id)
    drug.name = request.POST['name']
    drug.quantity = request.POST['quantity']
    drug.type = request.POST['type']
    drug.type_by_use = request.POST['type_by_use']
    drug.instruction = request.POST['instruction']
    drug.save()
    return HttpResponseRedirect(reverse('manager:dir_drugs'))


def del_drugs(request, id):
    Chemicals.objects.get(id=id).delete()
    return HttpResponseRedirect(reverse('manager:dir_drugs'))


def reg_drugs(request):
    profile = Chemicals.objects.create(name= request.POST['name'],
                                     quantity=request.POST['quantity'],
                                   type=request.POST['type'],
                                    type_by_use = request.POST['type_by_use'],
                                    instruction = request.POST['instruction'])
    profile.save()
    return HttpResponseRedirect(reverse('manager:dir_drugs'))


def add_servs(request):
    return render(request, 'manager/add_servs.html')


def dir_servs(request):
    a = Service.objects.all()
    config = {
        'servs': a
    }
    return render(request, 'manager/dir_servs.html', config)


def upd_servs(request, id):
    service = Service.objects.get(id=id)
    config = {
        'serv': service
    }
    return render(request, 'manager/upd_servs.html', config)


def update_servs(request, id):
    service = Service.objects.get(id=id)
    service.time = request.POST['time']
    service.ownership = request.POST['ownership']
    service.preparations = request.POST['preparations']
    service.total = request.POST['total']
    service.save()
    return HttpResponseRedirect(reverse('manager:dir_servs'))


def del_servs(request, id):
    Service.objects.get(id=id).delete()
    return HttpResponseRedirect(reverse('manager:dir_servs'))


def reg_servs(request):
    profile = Service.objects.create(name=request.POST['name'],
                                     time=request.POST['time'],
                                     ownership=request.POST['ownership'],
                                     preparations=request.POST['preparations'],
                                     total=request.POST['total'])
    profile.save()
    return HttpResponseRedirect(reverse('manager:dir_servs'))

dry_cleaning/templates/manager/add_drugs.html
{% extends 'manager/index.html' %}
{% block title %}Визначення вартісної оцінки{% endblock %}
{% block content %}
    {% load static %}
    <style>
    button#dir_drugs{
        background-color: #90A702;
    }
    </style>
    <form class="register" action={% url 'manager:reg_drugs' %} method='POST'>
        {% csrf_token %}
        <label>Додавання препарату</label>
        <div class="form-group">
            <label for="name">Назва препарату</label>
            <input class="form-control item" type="text" name="name" placeholder="Назва препарату" required>
        </div>
        <div class="form-group">
            <label for="type">Тип</label>
            <input class="form-control item" type="text" name="type" placeholder="Тип"
                   required>
        </div>
        <div class="form-group">
            <label for="type_by_use">Тип за використанням</label>
            <input class="form-control item" type="text" name="type_by_use" placeholder="Тип за використанням"
                   required>
        </div>
        <div class="form-group">
            <label for="quantity">Кількість</label>
            <input class="form-control item" type="text" name="quantity" placeholder="Кількість"
                   required>
        </div>
        <div class="form-group">
            <label for="instruction">Інструкція використання</label>
            <input class="form-control item" type="text" name="instruction" placeholder="Інструкція використання"
                   required>
        </div>

            <button class="btn btn-primary btn-block create-account" type="submit">Додати</button>

    </form>


{% endblock %}

dry_cleaning/templates/manager/add_possession.html
{% extends 'manager/index.html' %}
{% block title %}Визначення вартісної оцінки{% endblock %}
{% block content %}
    {% load static %}
    <style>
    button#dir_drugs{
        background-color: #90A702;
    }
    </style>
    <form class="register" action={% url 'manager:reg_possession' %} method='POST'>
        {% csrf_token %}
        <label>Додавання обладнання</label>
        <div class="form-group">
            <label for="first_name">Назва</label>
            <input class="form-control item" type="text" name="name" placeholder="Назва послуги" required>
        </div>
        <div class="form-group">
            <label for="last_name">Тип обладнання</label>
            <input class="form-control item" type="text" name="type" placeholder="Тип обладнання"
                   required>
        </div>
        <div class="form-group">
            <label for="phone">Назви послуг</label>
            <input class="form-control item" type="text" name="service" placeholder="Назви послуг"
                   required>
        </div>
        <div class="form-group">
            <label for="last_name">Тип хімічного препарату</label>
            <input class="form-control item" type="text" name="chemical" placeholder="Тип хімічного препарату"
                   required>
        </div>
        <div class="form-group">
            <label for="phone">Максимальна вага</label>
            <input class="form-control item" type="text" name="cost" placeholder="Максимальна вага"
                   required>
        </div>
        <div class="form-group">
            <label for="phone">Час на послугу</label>
            <input class="form-control item" type="time" name="hour" placeholder="Час на послугу"
                   required>
        </div>

            <button class="btn btn-primary btn-block create-account" type="submit">Додати</button>

    </form>


{% endblock %}

dry_cleaning/templates/manager/add_servs.html
{% extends 'manager/index.html' %}
{% block title %}Визначення вартісної оцінки{% endblock %}
{% block content %}
    {% load static %}
    <style>
    button#dir_drugs{
        background-color: #90A702;
    }
    </style>
    <form class="register" action={% url 'manager:reg_servs' %} method='POST'>
        {% csrf_token %}
        <label>Додавання сервісу</label>
        <div class="form-group">
            <label for="first_name">Назва послуги</label>
            <input class="form-control item" type="text" name="name" placeholder="Назва послуги" required>
        </div>
        <div class="form-group">
            <label for="last_name">Час виконання</label>
            <input class="form-control item" type="time" name="time" placeholder="Час виконання"
                   required>
        </div>
        <div class="form-group">
            <label for="phone">Обладнання</label>
            <input class="form-control item" type="text" name="ownership" placeholder="Обладнання"
                   required>
        </div>
        <div class="form-group">
            <label for="last_name">Хімічні препарати</label>
            <input class="form-control item" type="text" name="preparations" placeholder="Хімічні препарати"
                   required>
        </div>
        <div class="form-group">
            <label for="phone">Сума послуги</label>
            <input class="form-control item" type="text" name="total" placeholder="Сума послуги"
                   required>
        </div>

            <button class="btn btn-primary btn-block create-account" type="submit">Додати</button>

    </form>


{% endblock %}

dry_cleaning/templates/manager/dir_drugs.html
{% extends 'manager/index.html' %}
{% block title %}Визначення вартісної оцінки{% endblock %}
{% block content %}
    {% load static %}
    <style>
    button#dir_drugs{
        background-color: #90A702;
    }
    </style>
    <div>
    <div><input id="search-text" class="search" type="text" placeholder="Поиск" onkeyup="tableSearch()">
            <a href={% url 'manager:add_drugs' %}>
                <button class="btn btn-dark my-2 my-sm-0" type="submit">Додати</button>
            </a></div>
        <table id="info-table" class="table table_sort">

            <thead>
            <th>№</th>
            <th>Назва препарату</th>
            <th>Тип</th>
            <th>Тип за використанням</th>
            <th>Кількість</th>
            <th>Інструкція використання</th>
            <th></th>
            <th></th>
            </thead>
            <tbody>
            {% for drug in drugs %}
            <tr>
                <td>{{ drug.id }}</td>
                <td>{{ drug.name }}</td>
                <td>{{ drug.type }}</td>
                <td>{{ drug.type_by_use }}</td>
                <td>{{ drug.quantity }}</td>
                <td>{{ drug.instruction }}</td>
                <td>
                        <a href={% url 'manager:upd_drugs'  drug.id  %}>
                            <button class="btn btn-dark my-2 my-sm-0" type="submit">Update</button>
                        </a>
                    </td>
                    <td>
                        <a href={% url 'manager:del_drugs'  drug.id  %}>
                            <button class="btn btn-dark my-2 my-sm-0" type="submit">Delete</button>
                        </a>
                    </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

dry_cleaning/templates/manager/dir_servs.html
{% extends 'manager/index.html' %}
{% block title %}Визначення вартісної оцінки{% endblock %}
{% block content %}
    {% load static %}
    <style>
    button#dir_serv{
        background-color: #90A702;
    }
    </style>
    <div><div><input id="search-text" class="search" type="text" placeholder="Поиск" onkeyup="tableSearch()">
        <a href={% url 'manager:add_servs' %}>
                <button class="btn btn-dark my-2 my-sm-0" type="submit">Додати</button>
            </a></div>
        <table>
      <thead>
        <th>№</th>
        <th>Назва послуги</th>
        <th>Час виконання</th>
        <th>Обладнання</th>
        <th>Хімічні препарати</th>
        <th>Сума послуги</th>
        <th></th>
        <th></th>
      </thead>
      <tbody>
        {% for serv in servs %}
                <tr>
                    <td>{{ serv.id }}</td>
                    <td>{{ serv.name }}</td>
                    <td>{{ serv.time }}</td>
                    <td>{{ serv.ownership }}</td>
                    <td>{{ serv.preparations }}</td>
                    <td>{{ serv.total }}</td>
                    <td>
                        <a href={% url 'manager:upd_servs' serv.id%}>
                            <button class="btn btn-dark my-2 my-sm-0" type="submit">Update</button>
                        </a>
                    </td>
                    <td>
                        <a href={% url 'manager:del_servs' serv.id%}>
                            <button class="btn btn-dark my-2 my-sm-0" type="submit">Delete</button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
      </tbody>
    </table></div>


{% endblock %}

dry_cleaning/templates/manager/index.html
{% extends 'base.html' %} {% block title %}Приймальник замовлень{% endblock %}
{% block page %} {% load static %}
    <style>body{
        background-color: #FFC632;
    }
    button, input, label{
        background-color: #FFC632;
    }
    button:hover, input:hover{
        background-color: #90A702;
    }</style>
<div class="sidebar">
        {% if user.is_authenticated %}
            <div class="top">
                <li><a class="nav-link active" href={% url 'manager:shift' %}>
                    <button id="shift">Зміна</button>
                </a></li>
                <li><a class="nav-link active" href={% url 'manager:possession' %}>
                    <button id="possession">Обладнання</button>
                </a></li>
            <li><a class="nav-link active" href={% url 'manager:orders_done' %}>
                    <button id="orders_done">Виконані замов.</button>
                </a></li>
                <li><a class="nav-link active" href={% url 'manager:orders' %}>
                    <button id="orders">Не виконані замов.</button>
                </a></li>
            </div>
            <div class="down">
                <li><a class="nav-link active " href={% url 'manager:dir_servs' %}>
                    <button id="dir_serv">Довідник послуг</button>
                </a></li>
            <li><a class="nav-link active " href={% url 'manager:dir_drugs' %}>
                    <button id="dir_drugs">Довідник хімічних препаратів </button>
                </a></li>
            </div>

        {% endif %}
    </div>

    <div class="row">
{% block content %}{% endblock %}
    </div>
{% endblock %}

dry_cleaning/templates/manager/orders.html
{% extends 'manager/index.html' %}
{% block title %}Визначення вартісної оцінки{% endblock %}
{% block content %}
    {% load static %}
    <style>
    button#orders{
        background-color: #90A702;
    }
    </style>
    <div><input id="search-text" class="search" type="text" placeholder="Поиск" onkeyup="tableSearch()">
        <table id="info-table" class="table table_sort">

            <thead>
        <th>№</th>
        <th>Клиент</th>
        <th>Предмет одягу</th>
        <th>Тип услуги</th>
        <th>Сума за послугу</th>
        <th>Кількість</th>
        <th></th>
      </thead>
      <tbody>
       {% for order in orders %}
                <tr>
                    <td>{{ order.id }}</td>
                    <td>{{ order.client.user.first_name }} {{ order.client.user.last_name }}</td>
                    <td>{{ order.clothes }}</td>
                    <td>{{ order.service.name }}</td>
                    <td>{{ order.total }}</td>
                    <td>{{ order.quantity }}</td>
                    <td>
                        <a href={% url 'manager:order_done' order.id%}>
                            <button class="btn btn-dark my-2 my-sm-0" type="submit">Виконати</button>
                        </a>
                    </td>

                </tr>
            {% endfor %}
      </tbody>
        </table>
    </div>


{% endblock %}

dry_cleaning/templates/manager/possession.html
{% extends 'manager/index.html' %}
{% block title %}Визначення вартісної оцінки{% endblock %}
{% block content %}
    {% load static %}
    <style>
    button#possession{
        background-color: #90A702;
    }
    </style>
    <div><div><input id="search-text" class="search" type="text" placeholder="Поиск" onkeyup="tableSearch()">
            <a href={% url 'manager:add_possession' %}>
                <button class="btn btn-dark my-2 my-sm-0" type="submit">Додати</button>
            </a></div>
        <table id="info-table" class="table table_sort">

            <thead>
            <th>№</th>
            <th>Назва</th>
            <th>Тип обладнання</th>
            <th>Назви послуг</th>
            <th>Тип хімічного препарату</th>
            <th>Максимальна вага</th>
            <th>Час на послугу</th>
            <th>Дата огляду</th>
            <th></th>
            <th></th>
            </thead>
            <tbody>
            {% for poss in possessions %}
                <tr>
                    <td>{{ poss.id }}</td>
                    <td>{{ poss.name }}</td>
                    <td>{{ poss.type }}</td>
                    <td>{{ poss.service }}</td>
                    <td>{{ poss.chemical }}</td>
                    <td>{{ poss.cost }}</td>
                    <td>{{ poss.hour }}</td>
                    <td>{{ poss.date }}</td>

                    <td>
                        <a href={% url 'manager:upd_possession' poss.id%}>
                            <button class="btn btn-dark my-2 my-sm-0" type="submit">Update</button>
                        </a>
                    </td>
                    <td>
                        <a href={% url 'manager:del_possession' poss.id%}>
                            <button class="btn btn-dark my-2 my-sm-0" type="submit">Delete</button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}

dry_cleaning/templates/manager/shift.html
{% extends 'manager/index.html' %}
{% block title %}Визначення вартісної оцінки{% endblock %}
{% block content %}
    {% load static %}
    <style>
    button#shift{
        background-color: #90A702;
    }
    </style>
    <div><div><input id="search-text" class="search" type="text" placeholder="Поиск" onkeyup="tableSearch()">
        <table id="info-table" class="table table_sort">

            <thead>
            <th>№</th>
            <th>Працівник</th>
            <th>Посада</th>
            <th>Номер телефону</th>
            <th>Відроблених змін</th>
            <th></th>
            </thead>
            <tbody>
            {% for prof in profiles %}
                <tr>
                    <td>{{ prof.id }}</td>
                    <td>{{ prof.user.username }}</td>
                    <td>{{ prof.position }}</td>
                    <td>{{ prof.phone }}</td>
                    <td>{{ prof.total }}</td>
                    <td>
                        <a href={% url 'manager:add_shift' prof.id%}>
                            <button class="btn btn-dark my-2 my-sm-0" type="submit">+ Зміна</button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}

dry_cleaning/templates/manager/upd_drugs.html
{% extends 'manager/index.html' %}
{% block title %}Визначення вартісної оцінки{% endblock %}
{% block content %}
    {% load static %}
    <style>
    button#dir_drugs{
        background-color: #90A702;
    }
    </style>
    <form class="register" action={% url 'manager:reg_drugs' %} method='POST'>
        {% csrf_token %}
        <label>Редагування препарату</label>
        <div class="form-group">
            <label for="name">Назва препарату</label>
            <input class="form-control item" type="text" name="name" value="{{ drug.name }}" placeholder="Назва препарату" required>
        </div>
        <div class="form-group">
            <label for="type">Тип</label>
            <input class="form-control item" type="text" name="type" value="{{ drug.type }}" placeholder="Тип"
                   required>
        </div>
        <div class="form-group">
            <label for="type_by_use">Тип за використанням</label>
            <input class="form-control item" type="text" name="type_by_use" value="{{ drug.type_by_use }}" placeholder="Тип за використанням"
                   required>
        </div>
        <div class="form-group">
            <label for="quantity">Кількість</label>
            <input class="form-control item" type="text" name="quantity" value="{{ drug.quantity }}" placeholder="Кількість"
                   required>
        </div>
        <div class="form-group">
            <label for="instruction">Інструкція використання</label>
            <input class="form-control item" type="text" name="instruction" value="{{ drug.instruction }}" placeholder="Інструкція використання"
                   required>
        </div>

            <button class="btn btn-primary btn-block create-account" type="submit">Додати</button>

    </form>


{% endblock %}