dry_cleaning/apps/authorize/urls.py
from django.urls import path
from . import views

app_name = 'authorize'

urlpatterns = [
    path('',views.index, name='index'),
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('reg/', views.reg, name='reg'),
    path('log/', views.log, name='log'),
    path('log_out/', views.log_out, name='log_out'),
    # url('signup/', SignUpView.as_view(), name='signup'),
    path('getusers/', views.getusers, name='getusers'),
]

dry_cleaning/apps/director/urls.py
from django.urls import path
from . import views

app_name = 'director'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
path('analysis/', views.analysis, name='analysis'),
path('accounting/', views.accounting, name='accounting')
]

dry_cleaning/apps/manager/urls.py
from django.urls import path
from . import views

app_name = 'manager'

urlpatterns = [
    path('', views.index, name='index'),
    path('dir_drugs/', views.dir_drugs, name='dir_drugs'),
    path('add_drugs/', views.add_drugs, name='add_drugs'),
    path('reg_drugs/', views.reg_drugs, name='reg_drugs'),
    path('upd_drugs/<int:id>', views.upd_drugs, name='upd_drugs'),
    path('update_drugs/<int:id>', views.update_drugs, name='update_drugs'),
    path('del_drugs/<int:id>', views.del_drugs, name='del_drugs'),

    path('dir_servs/', views.dir_servs, name='dir_servs'),
    path('add_servs/', views.add_servs, name='add_servs'),
    path('reg_servs/', views.reg_servs, name='reg_servs'),
    path('upd_servs/<int:id>', views.upd_servs, name='upd_servs'),
    path('update_servs/<int:id>', views.update_servs, name='update_servs'),
    path('del_servs/<int:id>', views.del_servs, name='del_servs'),

    path('orders/', views.orders, name='orders'),
    path('order_done/<int:id>', views.order_done, name='order_done'),


    path('orders_done/', views.orders_done, name='orders_done'),


    path('possession/', views.possession, name='possession'),
    path('add_possession/', views.add_possession, name='add_possession'),
    path('reg_possession/', views.reg_possession, name='reg_possession'),
    path('upd_possession/<int:id>', views.upd_possession, name='upd_possession'),
    path('update_possession/<int:id>', views.update_possession, name='update_possession'),
    path('del_possession/<int:id>', views.del_possession, name='del_possession'),



    path('shift/', views.shift, name='shift'),
    path('add_shift/<int:id>', views.add_shift, name='add_shift')
]

dry_cleaning/apps/receiver/urls.py
from django.urls import path
from . import views

app_name = 'receiver'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_clients/', views.add_clients, name='add_clients'),
    path('reg_clients/', views.reg_clients, name='reg_clients'),
    path('upd_clients/<int:id>', views.upd_clients, name='upd_clients'),
    path('update_clients/<int:id>', views.update_clients, name='update_clients'),
    path('del_clients/<int:id>', views.del_clients, name='del_clients'),
    path('clients/', views.clients, name='clients'),


    path('services/', views.services, name='services'),
    path('add_services/', views.add_services, name='add_services'),
    path('reg_services/', views.reg_services, name='reg_services'),
    path('orders_done/', views.orders_done, name='orders_done'),
    path('services_done/', views.services_done, name='services_done'),
    path('upd_services/<int:id>', views.upd_services, name='upd_services'),
    path('update_services/<int:id>', views.update_services, name='update_services'),
    path('del_services/<int:id>', views.del_services, name='del_services'),


    path('orders/', views.orders, name='orders'),
    path('add_order/', views.add_order, name='add_order'),
    path('reg_orders/', views.reg_orders, name='reg_orders'),
    path('upd_orders/<int:id>', views.upd_orders, name='upd_orders'),
    path('update_orders/<int:id>', views.update_orders, name='update_orders'),
    path('del_orders/<int:id>', views.del_orders, name='del_orders')
]

dry_cleaning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('authorize.urls')),
    path('director/', include('director.urls')),
    path('manager/', include('manager.urls')),
    path('receiver/', include('receiver.urls')),
    path('admin/', admin.site.urls),
]

dry_cleaning/apps/authorize/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    position = models.TextField(max_length=500, blank=True)
    phone= models.TextField(max_length=500, blank=True)
    total= models.IntegerField(null=True)

dry_cleaning/apps/director/models.py
from django.db import models


class Expenses(models.Model):
    lease = models.IntegerField()
    utilities = models.IntegerField()
    equipment = models.IntegerField()
    salary = models.IntegerField()
    materials = models.IntegerField()
    preparations = models.IntegerField()
    date= models.DateTimeField(null=True)

dry_cleaning/apps/manager/models.py
from django.db import models
from django.contrib.auth.models import User


class Chemicals(models.Model):
    name = models.TextField(max_length=50, blank=True)
    quantity = models.IntegerField(blank=True)
    type = models.TextField()
    type_by_use = models.TextField()
    instruction = models.TextField()


class Shifts(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    position = models.TextField(max_length=50, blank=True)
    spent_changes = models.IntegerField(blank=True)

class Possession(models.Model):
    name = models.TextField(max_length=50, blank=True)
    type = models.TextField(max_length=50, blank=True)
    service = models.TextField(max_length=50, blank=True)
    chemical = models.TextField(max_length=50, blank=True)
    cost = models.TextField(max_length=50, blank=True)
    hour = models.TextField(max_length=50, blank=True)
    date = models.TextField(max_length=50, blank=True)

dry_cleaning/apps/receiver/models.py
from django.db import models
from django.contrib.auth.models import User

class Client(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone = models.TextField(null=True)


class Service(models.Model):
    name = models.TextField(max_length=50, blank=True)
    time = models.TextField(blank=True)
    ownership = models.TextField(null=True)
    preparations = models.TextField(null=True)
    total = models.IntegerField(blank=True)


class Order(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    status = models.TextField(max_length=50, blank=True)
    clothes = models.TextField(max_length=50, blank=True)
    quantity = models.IntegerField(blank=True)
    date_of_receipt = models.DateTimeField(null=True)
    date_of_issue = models.DateTimeField(null=True)
    date_of_process = models.DateTimeField(null=True)
    total = models.IntegerField(blank=True)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)

dry_cleaning/apps/authorize/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.models import User
from .models import *
from django.http import HttpResponseRedirect


def index(request):
    return render(request, 'base.html')


def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('authorize:index'))


def reg(request):
    UserModel = get_user_model()
    user = UserModel.objects.create_user(username=request.POST['username'],
                                         password=request.POST['password'])
    user.save()
    profile = Profile.objects.create(user=user,
                                     position=request.POST['position'],
                                         phone=request.POST['phone'],
                                     total=0)
    profile.save()
    return HttpResponseRedirect(reverse('authorize:signin'))


def log(request):
    user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
    if user is not None:
        login(request, user)
        print('Вход осуществлён')
        return HttpResponseRedirect(reverse('authorize:index'))
    else:
        print(user)
        print('Не получилось войти')
        return HttpResponseRedirect(reverse('authorize:signin'))


def getusers(request):
    a = User.objects.all()
    return render(request, 'registration/users.html', {'users': a})


def signup(request):
    return render(request, 'signup.html')


def signin(request):
    return render(request, 'authorize/login.html')

dry_cleaning/apps/director/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'director/index.html')

def register(request):
    return render(request, 'director/reg.html')
def accounting(request):
    return render(request, 'director/accounting.html')
def analysis(request):
    return render(request, 'director/analysis.html')

dry_cleaning/apps/manager/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.models import User
from .models import *
from receiver.models import *
from authorize.models import Profile
from django.http import HttpResponseRedirect
from datetime import date

def index(request):
    return render(request, 'manager/index.html')


def orders(request):
    a = Order.objects.all()
    list=[]
    for ord in a:
        if ord.status != "Success":
            list.append(ord)
    config = {
        'orders': list
    }
    return render(request, 'manager/orders.html',config)


def order_done(request,id):
    order = Order.objects.get(id=id)
    order.status ="Success"
    order.date_of_issue = date.today()
    order.save()
    return HttpResponseRedirect(reverse('manager:orders'))


def orders_done(request):
    a = Order.objects.all()
    list = []
    for ord in a:
        if ord.status == "Success":
            list.append(ord)
    config = {
        'orders': list
    }
    return render(request, 'manager/orders_done.html',config)


def possession(request):
    a = Possession.objects.all()
    config = {
        'possessions': a
    }
    return render(request, 'manager/possession.html', config)

def add_possession(request):

    return render(request, 'manager/add_possession.html', )

def upd_possession(request, id):
    drug = Possession.objects.get(id=id)
    config = {
        'poss': drug,
    }
    return render(request, 'manager/upd_possession.html', config)


def update_possession(request, id):
    possession = Possession.objects.get(id=id)
    possession.name = request.POST['name']
    possession.type = request.POST['type']
    possession.service = request.POST['service']
    possession.chemical = request.POST['chemical']
    possession.cost = request.POST['cost']
    possession.hour = request.POST['hour']
    possession.save()
    return HttpResponseRedirect(reverse('manager:possession'))


def del_possession(request, id):
    Possession.objects.get(id=id).delete()
    return HttpResponseRedirect(reverse('manager:possession'))


def reg_possession(request):
    profile = Possession.objects.create(name= request.POST['name'],
                                     type=request.POST['type'],
                                   service=request.POST['service'],
                                    chemical = request.POST['chemical'],
                                    cost = request.POST['cost'],
                                    hour = request.POST['hour'],
                                    date = date.today())
    profile.save()
    return HttpResponseRedirect(reverse('manager:possession'))


def shift(request):
    a = Profile.objects.all()
    config = {
        'profiles': a
    }
    return render(request, 'manager/shift.html',config)

def add_shift(request,id):
    prof = Profile.objects.get(id=id)
    prof.total+=1
    prof.save()
    return HttpResponseRedirect(reverse('manager:shift'))


def dir_drugs(request):
    a = Chemicals.objects.all()
    config = {
        'drugs': a
    }
    return render(request, 'manager/dir_drugs.html',config)

def add_drugs(request):
    config = {
    }
    return render(request, 'manager/add_drugs.html', config)

def upd_drugs(request, id):
    drug = Chemicals.objects.get(id=id)
    config = {
        'drug': drug,
    }
    return render(request, 'manager/upd_drugs.html', config)


def update_drugs(request, id):
    drug = Chemicals.objects.get(id=id)
    drug.name = request.POST['name']
    drug.quantity = request.POST['quantity']
    drug.type = request.POST['type']
    drug.type_by_use = request.POST['type_by_use']
    drug.instruction = request.POST['instruction']
    drug.save()
    return HttpResponseRedirect(reverse('manager:dir_drugs'))


def del_drugs(request, id):
    Chemicals.objects.get(id=id).delete()
    return HttpResponseRedirect(reverse('manager:dir_drugs'))


def reg_drugs(request):
    profile = Chemicals.objects.create(name= request.POST['name'],
                                     quantity=request.POST['quantity'],
                                   type=request.POST['type'],
                                    type_by_use = request.POST['type_by_use'],
                                    instruction = request.POST['instruction'])
    profile.save()
    return HttpResponseRedirect(reverse('manager:dir_drugs'))


def add_servs(request):
    return render(request, 'manager/add_servs.html')


def dir_servs(request):
    a = Service.objects.all()
    config = {
        'servs': a
    }
    return render(request, 'manager/dir_servs.html', config)


def upd_servs(request, id):
    service = Service.objects.get(id=id)
    config = {
        'serv': service
    }
    return render(request, 'manager/upd_servs.html', config)


def update_servs(request, id):
    service = Service.objects.get(id=id)
    service.time = request.POST['time']
    service.ownership = request.POST['ownership']
    service.preparations = request.POST['preparations']
    service.total = request.POST['total']
    service.save()
    return HttpResponseRedirect(reverse('manager:dir_servs'))


def del_servs(request, id):
    Service.objects.get(id=id).delete()
    return HttpResponseRedirect(reverse('manager:dir_servs'))


def reg_servs(request):
    profile = Service.objects.create(name=request.POST['name'],
                                     time=request.POST['time'],
                                     ownership=request.POST['ownership'],
                                     preparations=request.POST['preparations'],
                                     total=request.POST['total'])
    profile.save()
    return HttpResponseRedirect(reverse('manager:dir_servs'))

dry_cleaning/templates/director/accounting.html
{% extends 'director/index.html' %}
{% block title %}Визначення вартісної оцінки{% endblock %}
{% block content %}
{% load static %}
    <style>
    button#accounting{
        background-color: #FFC632;
    }
    </style>
    <table id="info-table" class="table table_sort" style="height: 50%">

            <thead>
            <th></th>
            <th>Січень</th>
            <th>Лютий</th>
            <th>Березень</th>
            <th>Квітень</th>
            <th>Травень</th>
            <th>Червень</th>
            <th>Липень</th>
            <th>Серпень</th>
            <th>Вересень</th>
            <th>Жовтень</th>
            <th>Листопад</th>
            <th>Грудень</th>
            </thead>
            <tbody>

            <tr>
                <td>Дохід</td>
                <td>32313</td>
                <td>5321</td>
                <td>42314</td>
                <td>54321</td>
                <td>4312</td>
                <td>4321</td>
                <td>643</td>
                <td>4213</td>
                <td>53425</td>
                <td>523</td>
                <td>5234</td>
                <td>53245</td>
            </tr>
            <tr>
                <td>Витрати</td>
                <td>53456</td>
                <td>66543</td>
                <td>5234</td>
                <td>4123</td>
                <td>342</td>
                <td>6423</td>
                <td>1324</td>
                <td>51243</td>
                <td>51234</td>
                <td>5231</td>
                <td>432</td>
                <td>312</td>
            </tr>
            <tr>
                <td>Різниця</td>
                <td>4123</td>
                <td>4123</td>
                <td>5231</td>
                <td>643</td>
                <td>4321</td>
                <td>5123</td>
                <td>62345</td>
                <td>543</td>
                <td>432</td>
                <td>65423</td>
                <td>4231</td>
                <td>6423</td>
            </tr>
            </tbody>
        </table>

{% endblock %}

dry_cleaning/templates/director/analysis.html
{% extends 'director/index.html' %}
{% block title %}Визначення вартісної оцінки{% endblock %}
{% block content %}
    {% load static %}
    <style>
        button#analysis {
            background-color: #FFC632;
        }


        li.ui-state-active {
            background-color: #FFC632 !important;
        }

        ul.tabs {
            display: grid;
            grid-template-columns: 1fr 1fr 1fr;
            grid-column-gap: 10px;
        }

        .tabs li {
            display: inline-block;
            padding: 10px;
            font-size: 20px;
            cursor: pointer;
            text-align: center;
            text-decoration: none;
            outline: none;
            color: black;
            background-color: #DD9324;
            border: black solid 3px;
            border-radius: 15px;
        }

        .tabs a {
            text-decoration: none;
            margin: 0;
            color: #000000;
        }
    </style>
    <script>
        $(function () {
            $("#tabs").tabs();
        });
    </script>
    </head>
    <body>

    <div id="tabs">
        <ul class="tabs">
            <li><a href="#tabs-1">Аналіз доходу</a></li>
            <li><a href="#tabs-2">Аналіз кількості замовлень</a></li>
            <li><a href="#tabs-3">Аналіз попиту послуг</a></li>
        </ul>
        <div id="tabs-1">
            <div class="diag" id="oil1"></div>
        </div>
        <div id="tabs-2">
            <div class="diag" id="oil2"></div>
        </div>
        <div id="tabs-3">
            <div class="diag" id="oil3"></div>
        </div>
    </div>
    <script>
        google.load("visualization", "1", {packages: ["corechart"]});
        google.setOnLoadCallback(drawChart);

        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['Год', 'Заробіток'],
                ['Січень', 13000],
                ['Лютий', 20000],
                ['Березень', 12170],
                ['Квітень', 22170],
                ['Травень', 15170],
                ['Червень', 21170],
                ['Липень', 17170],
                ['Серпень', 16170],
                ['Вересень', 13170],
                ['Жовтень', 19170],
                ['Листопад', 17170],
                ['Грудень', 15170]
            ]);
            var options = {
                hAxis: {title: 'Місяць'},
                vAxis: {title: 'Заробіток'},
                'width':1000,
                'height':400
            };
            var chart = new google.visualization.ColumnChart(document.getElementById('oil1'));
            chart.draw(data, options);
        }
    </script>
    <script>
        google.load("visualization", "1", {packages: ["corechart"]});
        google.setOnLoadCallback(drawChart);

        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['Год', 'Кількість замовлень'],
                ['Січень', 15],
                ['Лютий', 42],
                ['Березень', 32],
                ['Квітень', 64],
                ['Травень', 21],
                ['Червень', 34],
                ['Липень', 53],
                ['Серпень', 65],
                ['Вересень', 34],
                ['Жовтень', 54],
                ['Листопад', 32],
                ['Грудень', 23]
            ]);
            var options = {
                hAxis: {title: 'Кількість замовлень'},
                vAxis: {title: 'Місяць'},
                'width':1000,
                'height':400
            };
            var chart = new google.visualization.ColumnChart(document.getElementById('oil2'));
            chart.draw(data, options);
        }
    </script>
    <script>
        google.load("visualization", "1", {packages: ["corechart"]});
        google.setOnLoadCallback(drawChart);

        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['Год', 'Кількість'],
                ['Січень', 324],
                ['Лютий', 321],
                ['Березень', 545],
                ['Квітень', 321],
                ['Травень', 543],
                ['Червень', 321],
                ['Липень', 654],
                ['Серпень', 423],
                ['Вересень', 765],
                ['Жовтень', 432],
                ['Листопад', 543],
                ['Грудень', 432]
            ]);
            var options = {
                hAxis: {title: 'Кількість'},
                vAxis: {title: 'Місяць'},
                'width':1000,
                'height':400
            };
            var chart = new google.visualization.ColumnChart(document.getElementById('oil3'));
            chart.draw(data, options);
        }
    </script>
{% endblock %}

dry_cleaning/templates/director/index.html
{% extends 'base.html' %} {% block title %}Приймальник замовлень{% endblock %}
{% block page %} {% load static %}
    <style>body{
        background-color: #DD9324;
    }
    button, label, input{
        background-color: #DD9324;
    }
    button:hover, label:hover{
        background-color: #F6C57A;
    }</style>
<div class="sidebar">
        {% if user.is_authenticated %}
            <div class="top">
                <li><a class="nav-link active" href={% url 'director:accounting' %}>
                    <button id="accounting">Фінансовий облік</button>
                </a></li>
                <li><a class="nav-link active" href={% url 'director:analysis' %}>
                    <button id="analysis">Аналіз</button>
                </a></li>
            </div>
            <div class="down">
            <div></div>
                <li><a class="nav-link active " href={% url 'director:register' %}>
                    <button id="register">Реєстрація</button>
                </a></li>
            </div>

        {% endif %}
    </div>

    <div class="row">
    {% block content %} {% endblock %}
    </div>
{% endblock %}

dry_cleaning/templates/director/reg.html
{% extends 'director/index.html' %}
{% block title %}Визначення вартісної оцінки{% endblock %}
{% block content %}
{% load static %}
<style>
    button#register{
        background-color: #FFC632;
    }
    </style>
    <form class="register" action={% url 'authorize:reg' %} method='POST'>
      {% csrf_token %}
        <label>Додавання робітника</label>
        <div class="form-group">
            <label for="position">Посада</label>
            <select name="position" id="">
                <option value="Директор">Директор</option>
                <option value="Менеджер">Менеджер</option>
                <option value="Приймальник замовлень">Приймальник замовлень</option>
                <option value="Оператор сушильних машин">Оператор сушильних машин</option>
                <option value="Оператор пральних машин">Оператор пральних машин</option>
                <option value="Комплектувальник">Комплектувальник</option>
                <option value="Прасувальниця">Прасувальниця</option>
                <option value="Техноголог">Техноголог</option>
            </select>
        </div>
        <div class="form-group">
            <label for="">Мережа хімчисток</label>
            <select name="" id="">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </div>
        <div class="form-group">
            <label for="username">Логин</label>
            <input class="form-control item" type="text" name="username" placeholder="Логин" required>
        </div>
        <div class="form-group">
            <label for="password">Пароль</label>
            <input class="form-control item" type="password" name="password" placeholder="Пароль" required>
        </div>
        <div class="form-group">
            <label for="phone">Телефон</label>
            <input class="form-control item" type="text" name="phone" placeholder="Телефон" required>
        </div>
        <div class="form-group">
            <div></div>
            <button class="btn btn-primary btn-block create-account" type="submit">Вхiд</button>
        </div>
    </form>

{% endblock %}